### PR TITLE
chore(bindings): upgrade sourcemap and getrandom

### PR DESCRIPTION
**Pull request by Brooooooklyn**
Depends on https://github.com/parcel-bundler/lightningcss/pull/984

### CODE REVIEW

**Comment by kdy1** [comment]
Is this required to fix `error "ARM assembler must define __ARM_ARCH`?

**Comment by Brooooooklyn** [comment]
> error "ARM assembler must define __ARM_ARCH

This has been fixed, this is fix for upgrading `getrandom`, `getrandom` has significant breaking changes and is widely depended upon. Upgrading `getrandom` helps reduce compilation errors for users of swc.

**Comment by kdy1** [comment]
Can you take a look at https://github.com/swc-project/swc/actions/runs/15146697538/job/42584398787? It's still happening. Is it caused by https://github.com/swc-project/swc/commit/2212d3d688d5ca01e50b1ce8fb289d4f6b3e19d1 ?

**Comment by kdy1** [comment]
Closing as both crates are up-to-date
