### ISSUE TITLE
swc_ecma_utils-6.0.1 not compatible with swc_ecma_ast v5.0.2

### ISSUE THREAD

**Issue by BraveMole** [swc-project/swc#9906]
### Describe the bug

Compiling swc_ecma_utils-6.0.1 with swc_ecma_ast v5.0.2 generates the following error:

> unresolved imports `swc_ecma_ast::fast_id`, `swc_ecma_ast::FastId`
>  --> /home/bsouchu/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/swc_ecma_utils-6.0.1/src/ident.rs:3:20
>   |
> 3 | use swc_ecma_ast::{fast_id, BindingIdent, FastId, Id, Ident};

swc_ecma_utils-6.0.1 compiles fine with swc_ecma_ast v5.0.1

This was discovered here:

https://github.com/leptos-rs/cargo-leptos/issues/419

### Input code

```typescript

```

### Config

```json

```

### Playground link (or link to the minimal reproduction)

https://github.com/leptos-rs/cargo-leptos/issues/419

### Expected behavior

If it compiles with 5.0.1, it should also compile with 5.0.2 or that's a semver violation

### Actual behavior

Compilation error

### Version

swc_ecma_ast v5.0.2

### Additional context

Unsure if this is the correct repo to post the issue

**Comment by kdy1** [comment]
It sems like it's caused by a version bump mistake. I'll publish a new version to fix it.

**Comment by kdy1** [comment]
Actually the problem is that `cargo` selects an outdated version of `swc_ecma_utils`
