### PR TITLE
chore: Publish `v1.3.17`

### PR DESCRIPTION
**Pull request by kdy1**

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - dbg-swc

**Comment by kdy1** [comment]
cc @kwonoj I reverted https://github.com/swc-project/swc/commit/1dd8b3d9d5393fa382345dce3d6977f7d4b5aa63 as it broke wasm

**Comment by kwonoj** [comment]
@kdy1 can I see Ci logs to fix it forward?

**Comment by kdy1** [comment]
https://github.com/swc-project/swc/actions/runs/3467260819/jobs/5791963901

**Comment by kdy1** [comment]
Oh revert was not enough

**Comment by kwonoj** [comment]
Let bindings use published version of swc_core serves well, but we definitely need some way to test latest swc_core directly before publishing bindings :/ I'll file an issue and think about some way.

**Comment by kdy1** [comment]
It does not work. With the latest version wasm CI fails

**Comment by kdy1** [comment]
See https://github.com/swc-project/swc/actions/runs/3467460473/jobs/5792360658
It's using `binding_macros@ v0.20.94`

**Comment by kwonoj** [comment]
> It does not work. With the latest version wasm CI fails

Do you mean previous version of swc_core, or one more bump of swc_core with revert? if it's reverted + swc_core has been bumped up and still same compilation error occurs?

**Comment by kdy1** [comment]
No, it's not reverted yet and the broken version (with #6436) is the latest version at the moment

**Comment by kwonoj** [comment]
I see.

What I meant

> Let bindings use published version of swc_core serves well, 

was not for this specific case, it's for more general cases (aka `when it works, it works well`). As said above, seems we're hitting bumps bit more than we expected - I'll try to see if I can come up with some plan.
